MoviesInfo/Areas/User/Pages/Favorites.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MoviesInfo.Data;
using MoviesInfo.Data.Entities;

namespace MoviesInfo.Areas.User.Pages
{
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class FavoritesModel : PageModel
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<CustomUser> userManager;

        public FavoritesModel(ApplicationDbContext context, UserManager<CustomUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        public List<FavoriteModel> Favorites { get; set; }

        public async Task<IActionResult> OnGet()
        {
            var user = await GetUserModel();
            if(user.Favorites != null)
            {
                Favorites = user.Favorites;
            }
            
            return Page();
        }

        public async Task<IActionResult> OnPostUnfollow(int? showId)
        {
            if (showId == null)
            {
                return NotFound();
            }
            var user = await GetUserModel();
            if (user != null)
            {
                var favorite = user.Favorites.First(f => f.ShowId == showId);
                if(favorite != null)
                {
                    context.Favorites.Remove(favorite);
                    context.SaveChanges();
                }
            }

            return RedirectToPage("/Favorites");
        }

        private async Task<CustomUser> GetUserModel()
        {
            if (User.Identity.IsAuthenticated)
            {
                return await context.Users
                .Include(u => u.Favorites)
                .ThenInclude(f => f.Show)
                .FirstAsync(u => u.Id == userManager.GetUserId(User));
            }
            return null;
        }
    }
}

MoviesInfo/Areas/User/Pages/Favorites.cshtml
@page
@model MoviesInfo.Areas.User.Pages.FavoritesModel
@{
    ViewData["Title"] = "Favorites";
    ViewData["Header"] = "Favorites shows";
}
@foreach (var item in Model.Favorites)
{
    <div class="container p-0 d-flex align-content-stretch mb-4">
        <div class="flex-grow-0 mr-2">
            <img style="max-width:150px;" class="border border-primary rounded" src="@item.Show.Portrait" />
        </div>
        <div class="card border-dark flex-grow-1">
            <div class="card-header bg-dark">
                <h3 class="card-title text-white mb-0">@Html.DisplayFor(modelItem => item.Show.Name)</h3>
            </div>
            <div class="card-body">
                @Html.DisplayFor(modelItem => item.Show.Description)
            </div>
            <form class="card-footer d-flex justify-content-between" method="post">
                    <input type="hidden" asp-for="@item.ShowId" name="showId" />
                    <button class="btn btn-danger" asp-page-handler="Unfollow">Unfollow</button>
                    <a class="page-link" asp-area="Show" asp-page="/More" asp-route-id="@item.Show.Id">More details</a>
            </form>
        </div>
    </div>
}