MoviesInfo/Areas/Admin/Pages/Show/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MoviesInfo.Data;
using MoviesInfo.Data.Entities;

namespace MoviesInfo.Areas.Admin.Pages.Show
{
    public class CreateModel : PageModel
    {
        private readonly MoviesInfo.Data.ApplicationDbContext _context;

        public CreateModel(MoviesInfo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public ShowModel ShowModel { get; set; }

        [BindProperty]
        public IFormFile PortaritFile { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            string imageName = await CreatePortrait(PortaritFile, ShowModel);

            ShowModel.Portrait = $"/images/{imageName}.jpg ";
            _context.Shows.Add(ShowModel);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        private async Task<string> CreatePortrait(IFormFile file, ShowModel model)
        {
            string imageName = model.Name + model.Description + DateTime.Now;
            using (Stream stream = file.OpenReadStream())
            {
                using (SHA256 sha256 = SHA256.Create())
                {
                    byte[] buffer = Encoding.UTF8.GetBytes(imageName);
                    imageName = BitConverter.ToString(sha256.ComputeHash(buffer, 0, buffer.Length)).Replace("-", "");

                    using (FileStream fs = new FileStream($"wwwroot/images/{imageName}.jpg", FileMode.OpenOrCreate, FileAccess.Write))
                    {
                        await stream.CopyToAsync(fs);
                    }
                }
            }

            return imageName;
        }
    }
}

MoviesInfo/Areas/Admin/Pages/Show/DelFile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MoviesInfo.Areas.Admin.Pages.Show
{
    public class DelFileModel : PageModel
    {
        public void OnGet()
        {
            string path = "wwwroot/images/9CDBEC2262975DCD2113DD54946C5353D0EDD1820B34AD4A399785BE666EA51D.jpg";
            System.IO.File.Delete(path);
        }
    }
}

MoviesInfo/Areas/Admin/Pages/Show/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MoviesInfo.Data.Entities;

namespace MoviesInfo.Areas.Admin.Pages.Show
{
    public class DeleteModel : PageModel
    {
        private readonly MoviesInfo.Data.ApplicationDbContext context;
        private readonly ILogger<DeleteModel> logger;

        public DeleteModel(MoviesInfo.Data.ApplicationDbContext context, ILogger<DeleteModel> logger)
        {
            this.context = context;
            this.logger = logger;
        }

        [BindProperty]
        public ShowModel ShowModel { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ShowModel = await context.Shows.FirstOrDefaultAsync(m => m.Id == id);

            if (ShowModel == null)
            {
                return NotFound();
            }
            
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ShowModel = await context.Shows
                .Include(m => m.Details)
                .FirstAsync(s => s.Id == id);
            
            if (ShowModel != null)
            {
                context.Shows.Remove(ShowModel);
                await context.SaveChangesAsync();
            }
            

            return RedirectToPage("./Index");
        }
    }
}

MoviesInfo/Areas/Admin/Pages/Show/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MoviesInfo.Data;
using MoviesInfo.Data.Entities;

namespace MoviesInfo.Areas.Admin.Pages.Show
{
    public class DetailsModel : PageModel
    {
        private readonly MoviesInfo.Data.ApplicationDbContext context;

        public DetailsModel(MoviesInfo.Data.ApplicationDbContext context)
        {
            this.context = context;
        }

        public ShowModel ShowModel { get; set; }

        public List<Data.Entities.EpisodeModel> EpisodeModel { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ShowModel = await context.Shows.Include(s => s.Details).FirstOrDefaultAsync(m => m.Id == id);
            EpisodeModel = await context.Episodes.Where(e => e.Show.Id == id).ToListAsync();
            if (EpisodeModel == null)
            {
                return NotFound();
            }
            if(ShowModel == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

MoviesInfo/Areas/Admin/Pages/Show/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesInfo.Data;
using MoviesInfo.Data.Entities;

namespace MoviesInfo.Areas.Admin.Pages.Show
{
    public class EditModel : PageModel
    {
        private readonly MoviesInfo.Data.ApplicationDbContext context;

        public EditModel(MoviesInfo.Data.ApplicationDbContext context)
        {
            this.context = context;
        }

        [BindProperty]
        public ShowModel ShowModel { get; set; }

        [BindProperty]
        public IFormFile PortaritFile { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ShowModel = await context.Shows
                .Include(s => s.Details)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (ShowModel == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if(PortaritFile != null)
            {
                string imageName = await CreatePortrait(PortaritFile, ShowModel);
                ShowModel.Portrait = $"/images/{imageName}.jpg";
            }

            context.Update(ShowModel);

            try
            {
                await context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ShowModelExists(ShowModel.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ShowModelExists(int id)
        {
            return context.Shows.Any(e => e.Id == id);
        }

        private async Task<string> CreatePortrait(IFormFile file, ShowModel model)
        {
            string imageName = model.Name + model.Description + DateTime.Now;
            using (Stream stream = file.OpenReadStream())
            {
                using (SHA256 sha256 = SHA256.Create())
                {
                    byte[] buffer = Encoding.UTF8.GetBytes(imageName);
                    imageName = BitConverter.ToString(sha256.ComputeHash(buffer, 0, buffer.Length));

                    using (FileStream fs = new FileStream($"wwwroot/images/{imageName}.jpg", FileMode.OpenOrCreate, FileAccess.Write))
                    {
                        await stream.CopyToAsync(fs);
                    }
                }
            }

            return imageName;
        }
    }
}

MoviesInfo/Areas/Admin/Pages/Show/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MoviesInfo.Data;
using MoviesInfo.Data.Entities;

namespace MoviesInfo.Areas.Admin.Pages.Show
{
    public class IndexModel : PageModel
    {
        private readonly MoviesInfo.Data.ApplicationDbContext _context;

        public IndexModel(MoviesInfo.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Data.Entities.ShowModel> ShowModel { get;set; }

        public async Task OnGetAsync()
        {
            ShowModel = await _context.Shows.ToListAsync();
        }
    }
}

MoviesInfo/Areas/Admin/Pages/Show/New.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MoviesInfo.Areas.Admin.Pages.Show
{
    public class NewModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MoviesInfo/Areas/Show/Pages/More.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MoviesInfo.Data;
using MoviesInfo.Data.Entities;

namespace MoviesInfo.Areas.Show.Pages
{
    public class MoreModel : PageModel
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<CustomUser> userManager;

        public MoreModel(ApplicationDbContext context, UserManager<CustomUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        public bool IsFollow { get; set; }
        public ShowModel ShowModel { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ShowModel = await context.Shows
                .Include(s => s.Details)
                .Include(s => s.Episodes)
                .FirstOrDefaultAsync(m => m.Id == id);

            var user = await GetUserModel();
            if(user != null)
            {
                if (ShowModel == null)
                {
                    return NotFound();
                }
                if (user == null)
                {
                    return Redirect("/");
                }

                IsFollow = user.Favorites.Where(f => f.ShowId == id).Any();
            }
            
            return Page();
        }

        public async Task<IActionResult> OnPostFollow(int? showId)
        {
            if(showId == null)
            {
                return NotFound();
            }
            var user = await GetUserModel();
            if(user != null)
            {
                var favorite = new FavoriteModel()
                {
                    ShowId = (int)showId
                };

                if (!IsFollow)
                {
                    user.Favorites.Add(favorite);
                    context.Users.Update(user);
                    context.SaveChanges();
                }
            }

            return RedirectToPage("/More", new { id = showId });
        }

        private async Task<CustomUser> GetUserModel()
        {
            if(User.Identity.IsAuthenticated)
            {
                return await context.Users
                .Include(u => u.Favorites)
                .FirstAsync(u => u.Id == userManager.GetUserId(User));
            }
            return null;
        }
    }
}

MoviesInfo/Areas/Show/Pages/Series.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MoviesInfo.Areas.Show.Pages
{
    public class SeriesModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MoviesInfo/Areas/Show/Pages/More.cshtml
@page
@model MoviesInfo.Areas.Show.Pages.MoreModel
@{
    ViewData["Title"] = "More";
    ViewData["Header"] = "More details";
}

<div class="container p-0 mb-4">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link active" asp-area="Show" asp-page="/More">More details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Show" asp-page="/Series">Series</a>
        </li>
    </ul>
</div>

<div class="container p-0 d-flex align-content-stretch mb-4">
    <div class="flex-grow-0 mr-2">
        <img class="border border-primary rounded" style="max-height:400px;" src="@Html.DisplayFor(model => model.ShowModel.Portrait)"/>
    </div>
    <div class="card border-dark flex-grow-1">
        <div class="card-header bg-dark">
            <h3 class="card-title text-white mb-0">@Html.DisplayFor(model => model.ShowModel.Name)</h3>
        </div>
        <div class="card-body">
            @Html.DisplayFor(model => model.ShowModel.Description)
        </div>
        <form class="card-footer" method="post">
            <input type="hidden" asp-for="ShowModel.Id" name="showId" />
            @if (Model.IsFollow)
            {
                <span class="btn btn-secondary">Following</span>
            }
            else
            {
                @if (User.Identity.IsAuthenticated)
                {
                    <button class="btn btn-success" asp-page-handler="Follow">Follow</button>
                }
                else
                {
                    <button class="btn btn-success" disabled asp-page-handler="Follow">Follow</button>
                }
            }
        </form>
    </div>
</div>

<div class="container p-0 mb-4">
    <ul class="list-group">
        <li class="list-group-item list-group-item-primary">Show Info</li>
        @if (Model.ShowModel.Details.Network != null)
        {
            <li class="list-group-item list-group-item-light">
                <b>@Html.DisplayNameFor(model => model.ShowModel.Details.Network)</b>
                @Html.DisplayFor(model => model.ShowModel.Details.Network)
            </li>
        }
        @if (Model.ShowModel.Details.Schedule != null)
        {
            <li class="list-group-item list-group-item-light">
                <b>@Html.DisplayNameFor(model => model.ShowModel.Details.Schedule)</b>
                @Html.DisplayFor(model => model.ShowModel.Details.Schedule)
            </li>
        }
        <li class="list-group-item list-group-item-light">
            <b>@Html.DisplayNameFor(model => model.ShowModel.Details.Genres)</b>
            @Html.DisplayFor(model => model.ShowModel.Details.Genres)
        </li>
        <li class="list-group-item list-group-item-light">
            <b>@Html.DisplayNameFor(model => model.ShowModel.Details.Developer)</b>
            @Html.DisplayFor(model => model.ShowModel.Details.Developer)
        </li>
    </ul>
</div>

@if(Model.ShowModel.Episodes.Count > 0)
{
<div class="container p-0">
    <table class="table border border-dark">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Number</th>
                <th scope="col">Episode Name</th>
                <th scope="col">Airdate</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ShowModel.Episodes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Season)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EpisodeName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AirDate)
                    </td>
                    <td class="d-flex justify-content-end p-1">
                        <a class="page-link" asp-page="/Episode/Edit" asp-route-id="@item.Id">Edit</a>
                        <a class="page-link" asp-page="/Episode/Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
}

MoviesInfo/Areas/Show/Pages/Series.cshtml
@page
@model MoviesInfo.Areas.Show.Pages.SeriesModel
@{
    ViewData["Title"] = "Series";
    ViewData["Header"] = "Series";
}

<div class="container p-0 mb-4">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link" asp-area="Show" asp-page="/More">More details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" asp-area="Show" asp-page="/Series">Series</a>
        </li>
    </ul>
</div>

<div class="container p-0">
    <table class="table border border-dark mb-0">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Number</th>
                <th scope="col">Episode Name</th>
                <th scope="col">Airdate</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>Dsdss</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>Dsdss</td>
            </tr>
        </tbody>
    </table>
    <table class="table border border-dark">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Number</th>
                <th scope="col">Episode Name</th>
                <th scope="col">Airdate</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>Dsdss</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>Dsdss</td>
            </tr>
        </tbody>
    </table>
</div>